/// Translatable UI strings for the CLI.
/// Supported locales: en, fr, es, de, pt.

pub struct Lang {
    // Validation errors
    pub invalid_test_type: &'static str,
    pub invalid_cooling_type: &'static str,

    // Hardware detection
    pub detecting_hardware: &'static str,
    pub laptop_detected: &'static str,
    pub unknown: &'static str,
    pub not_available: &'static str,

    // Test type prompt
    pub what_to_test: &'static str,
    pub cpu_only: &'static str,
    pub gpu_only: &'static str,
    pub cpu_gpu_recommended: &'static str,
    pub enter_choice_test: &'static str,

    // Duration prompt
    pub how_long_stress: &'static str,
    pub recommend_note: &'static str,
    pub recommend_reason: &'static str,
    pub dur_60: &'static str,
    pub dur_120: &'static str,
    pub dur_180: &'static str,
    pub dur_300: &'static str,
    pub dur_custom: &'static str,
    pub enter_choice_duration: &'static str,
    pub enter_duration_secs: &'static str,
    pub min_duration_30: &'static str,

    // Laptop model prompt
    pub laptop_model_prompt: &'static str,
    pub laptop_model_examples: &'static str,
    pub laptop_model_input: &'static str,

    // Cooling type prompt
    pub cooling_type_prompt: &'static str,
    pub cooling_stock: &'static str,
    pub cooling_air: &'static str,
    pub cooling_aio: &'static str,
    pub cooling_custom_loop: &'static str,
    pub cooling_passive: &'static str,
    pub cooling_other: &'static str,
    pub skip: &'static str,
    pub enter_choice_cooling: &'static str,

    // Cooling model prompt
    pub cooling_model_prompt: &'static str,
    pub cooling_model_examples: &'static str,
    pub cooling_model_input: &'static str,

    // Ambient temperature prompt
    pub ambient_temp_prompt: &'static str,
    pub ambient_temp_hint: &'static str,
    pub room_temp_input: &'static str,
    pub cant_parse_temp: &'static str,

    // LHM / Windows sensor
    pub extracting_sensor: &'static str,
    pub sensor_ready: &'static str,
    pub pawnio_installing: &'static str,
    pub pawnio_installed: &'static str,
    pub pawnio_removable: &'static str,
    pub pawnio_detected: &'static str,
    pub pawnio_failed: &'static str,
    pub requires_admin_msg: &'static str,
    pub right_click_msg: &'static str,
    pub continuing_board: &'static str,

    // Temperature labels
    pub idle: &'static str,
    pub load: &'static str,

    // Stress test
    pub running_stress: &'static str,
    pub press_ctrl_c: &'static str,
    pub spawned_cpu_threads: &'static str,
    pub starting_gpu_stress: &'static str,
    pub webgpu_fallback: &'static str,
    pub complete: &'static str,

    // Results summary
    pub results_summary: &'static str,
    pub cpu_idle_label: &'static str,
    pub cpu_load_label: &'static str,
    pub gpu_idle_label: &'static str,
    pub gpu_load_label: &'static str,
    pub cpu_max_usage: &'static str,
    pub gpu_max_usage: &'static str,
    pub cooling_label: &'static str,
    pub laptop_label: &'static str,
    pub cooler_label: &'static str,
    pub ambient_label: &'static str,

    // Cooling type display labels
    pub label_stock: &'static str,
    pub label_air: &'static str,
    pub label_aio: &'static str,
    pub label_custom_loop: &'static str,
    pub label_passive: &'static str,
    pub label_other: &'static str,

    // Board sensor warning
    pub board_sensor_warning: &'static str,
    pub rerun_admin: &'static str,

    // Submission
    pub submitting: &'static str,
    pub submitted_view: &'static str,
    pub prod_unreachable: &'static str,
    pub submitted_local: &'static str,
    pub failed_submit: &'static str,
    pub not_saved_online: &'static str,
    pub skipping_submit: &'static str,
    pub stale_temps_skip: &'static str,
    pub api_rejected: &'static str,

    // Final
    pub done: &'static str,
    pub window_closing: &'static str,
    pub closing_in: &'static str,
    pub goodbye: &'static str,
    pub opening_browser: &'static str,

    // PawnIO post-test prompt
    pub pawnio_keep_prompt: &'static str,
    pub pawnio_keep_yes: &'static str,
    pub pawnio_keep_no: &'static str,
    pub pawnio_keep_timeout: &'static str,
    pub pawnio_enter_choice: &'static str,
    pub pawnio_kept: &'static str,
    pub pawnio_uninstalling: &'static str,
    pub pawnio_uninstalled: &'static str,
    pub pawnio_uninstall_failed: &'static str,
}

pub fn detect_locale(override_lang: Option<&str>) -> String {
    if let Some(lang) = override_lang {
        return normalize_locale(lang);
    }
    sys_locale::get_locale()
        .map(|l| normalize_locale(&l))
        .unwrap_or_else(|| "en".to_string())
}

fn normalize_locale(locale: &str) -> String {
    let lower = locale.to_lowercase();
    // Extract the language code (first 2 chars before any separator)
    let code = lower
        .split(|c: char| c == '-' || c == '_')
        .next()
        .unwrap_or("en");
    match code {
        "fr" | "es" | "de" | "pt" => code.to_string(),
        _ => "en".to_string(),
    }
}

impl Lang {
    pub fn new(locale: &str) -> Self {
        match locale {
            "fr" => Self::fr(),
            "es" => Self::es(),
            "de" => Self::de(),
            "pt" => Self::pt(),
            _ => Self::en(),
        }
    }

    fn en() -> Self {
        Self {
            invalid_test_type: "Invalid test type '{}'. Use: cpu, gpu, or both",
            invalid_cooling_type: "Invalid cooling type '{}'. Use: stock, air, aio, custom_loop, passive, or other",
            detecting_hardware: "Detecting hardware...",
            laptop_detected: "Laptop detected",
            unknown: "Unknown",
            not_available: "Not available",
            what_to_test: "What would you like to test?",
            cpu_only: "CPU only",
            gpu_only: "GPU only",
            cpu_gpu_recommended: "CPU + GPU (recommended)",
            enter_choice_test: "Enter choice (1/2/3)",
            how_long_stress: "How long should the stress test run?",
            recommend_note: "We recommend at least 120 seconds so cooling systems have time to",
            recommend_reason: "fully engage and give realistic sustained temperatures.",
            dur_60: " 60 seconds  (quick)",
            dur_120: "120 seconds  (recommended)",
            dur_180: "180 seconds  (thorough)",
            dur_300: "300 seconds  (extended)",
            dur_custom: "Custom",
            enter_choice_duration: "Enter choice (1-5)",
            enter_duration_secs: "Enter duration in seconds:",
            min_duration_30: "Minimum duration is 30 seconds, using 30s.",
            laptop_model_prompt: "What laptop model do you have? (optional)",
            laptop_model_examples: "e.g. ASUS ROG Zephyrus G14, Dell XPS 15, Lenovo Legion 5 Pro",
            laptop_model_input: "Laptop model (Enter to skip):",
            cooling_type_prompt: "What type of CPU cooling do you use?",
            cooling_stock: "Stock Cooler",
            cooling_air: "Aftermarket Air Cooler",
            cooling_aio: "AIO Liquid Cooler",
            cooling_custom_loop: "Custom Water Loop",
            cooling_passive: "Passive / Fanless",
            cooling_other: "Other",
            skip: "Skip",
            enter_choice_cooling: "Enter choice (1-6) or Enter to skip:",
            cooling_model_prompt: "What cooler model do you have? (optional)",
            cooling_model_examples: "e.g. Noctua NH-D15, Corsair H150i, be quiet! Dark Rock Pro 4",
            cooling_model_input: "Cooler model (Enter to skip):",
            ambient_temp_prompt: "What\u{2019}s your ambient room temperature? (optional)",
            ambient_temp_hint: "Enter a number in \u{00b0}C or add 'f' for Fahrenheit (e.g. 22, 72f)",
            room_temp_input: "Room temp (Enter to skip):",
            cant_parse_temp: "Couldn't parse temperature, skipping.",
            extracting_sensor: "Extracting sensor library...",
            sensor_ready: "Sensor library ready (accurate CPU die temps enabled)",
            pawnio_installing: "Installing PawnIO driver (pawnio.eu) \u{2014} a free utility required for CPU temperature reading...",
            pawnio_installed: "PawnIO driver installed successfully.",
            pawnio_removable: "You can uninstall PawnIO from Add & Remove Programs if you wish.",
            pawnio_detected: "PawnIO driver detected (pawnio.eu) \u{2014} required for CPU temperature reading.",
            pawnio_failed: "PawnIO driver installation failed \u{2014} CPU die temps may be unavailable.",
            requires_admin_msg: "This tool requires running as Administrator for accurate CPU temperatures.",
            right_click_msg: "Right-click your terminal \u{2192} Run as administrator",
            continuing_board: "Continuing with board-level sensors (less accurate)...",
            idle: "Idle",
            load: "Load",
            running_stress: "Running {} stress test for {}s...",
            press_ctrl_c: "Press Ctrl+C to stop early.",
            spawned_cpu_threads: "Spawned {} CPU stress threads",
            starting_gpu_stress: "Starting GPU stress (WebGPU compute on {})",
            webgpu_fallback: "WebGPU not available ({}), using CPU-based FP stress",
            complete: "Complete!",
            results_summary: "RESULTS SUMMARY",
            cpu_idle_label: "CPU Idle:",
            cpu_load_label: "CPU Load:",
            gpu_idle_label: "GPU Idle:",
            gpu_load_label: "GPU Load:",
            cpu_max_usage: "CPU Max Usage:",
            gpu_max_usage: "GPU Max Usage:",
            cooling_label: "Cooling:",
            laptop_label: "Laptop:",
            cooler_label: "Cooler:",
            ambient_label: "Ambient:",
            label_stock: "Stock Cooler",
            label_air: "Aftermarket Air",
            label_aio: "AIO Liquid",
            label_custom_loop: "Custom Loop",
            label_passive: "Passive / Fanless",
            label_other: "Other",
            board_sensor_warning: "CPU temp didn't change \u{2014} reading is from a board-level sensor.",
            rerun_admin: "Re-run as Administrator for accurate CPU die temps.",
            submitting: "Submitting results...",
            submitted_view: "Submitted! View at:",
            prod_unreachable: "Production API unreachable, trying localhost...",
            submitted_local: "Submitted to local server! View at:",
            failed_submit: "Failed to submit:",
            not_saved_online: "Results were displayed above but not saved online.",
            skipping_submit: "Skipping submission (--no-submit flag).",
            stale_temps_skip: "Skipping submission \u{2014} CPU temperature didn't change between idle and load.\n  Re-run as Administrator for accurate CPU die temps.",
            api_rejected: "Submission rejected:",
            done: "Done!",
            window_closing: "Window will close in 30 seconds. Press Ctrl+C to exit now.",
            closing_in: "Closing in {}s...",
            goodbye: "Goodbye!",
            opening_browser: "Opening results in your browser...",
            pawnio_keep_prompt: "Do you want to leave the PawnIO driver installed? It's a lightweight, free,\n  open-source driver useful for hardware monitoring. (https://github.com/namazso/PawnIO)",
            pawnio_keep_yes: "Yes, keep installed",
            pawnio_keep_no: "No, uninstall",
            pawnio_keep_timeout: "No response in {}s — PawnIO will remain installed.",
            pawnio_enter_choice: "Enter choice (1-2) — defaults to 1 in {}s:",
            pawnio_kept: "PawnIO driver will remain installed.",
            pawnio_uninstalling: "Uninstalling PawnIO driver...",
            pawnio_uninstalled: "PawnIO driver uninstalled.",
            pawnio_uninstall_failed: "PawnIO uninstall failed:",
        }
    }

    fn fr() -> Self {
        Self {
            invalid_test_type: "Type de test invalide '{}'. Utilisez : cpu, gpu ou both",
            invalid_cooling_type: "Type de refroidissement invalide '{}'. Utilisez : stock, air, aio, custom_loop, passive ou other",
            detecting_hardware: "D\u{00e9}tection du mat\u{00e9}riel...",
            laptop_detected: "Ordinateur portable d\u{00e9}tect\u{00e9}",
            unknown: "Inconnu",
            not_available: "Non disponible",
            what_to_test: "Que souhaitez-vous tester ?",
            cpu_only: "CPU uniquement",
            gpu_only: "GPU uniquement",
            cpu_gpu_recommended: "CPU + GPU (recommand\u{00e9})",
            enter_choice_test: "Entrez votre choix (1/2/3)",
            how_long_stress: "Combien de temps le test de stress doit-il durer ?",
            recommend_note: "Nous recommandons au moins 120 secondes pour que le refroidissement",
            recommend_reason: "se stabilise et donne des temp\u{00e9}ratures r\u{00e9}alistes.",
            dur_60: " 60 secondes  (rapide)",
            dur_120: "120 secondes  (recommand\u{00e9})",
            dur_180: "180 secondes  (approfondi)",
            dur_300: "300 secondes  (prolong\u{00e9})",
            dur_custom: "Personnalis\u{00e9}",
            enter_choice_duration: "Entrez votre choix (1-5)",
            enter_duration_secs: "Entrez la dur\u{00e9}e en secondes :",
            min_duration_30: "Dur\u{00e9}e minimale de 30 secondes, utilisation de 30s.",
            laptop_model_prompt: "Quel est votre mod\u{00e8}le d'ordinateur portable ? (optionnel)",
            laptop_model_examples: "ex. ASUS ROG Zephyrus G14, Dell XPS 15, Lenovo Legion 5 Pro",
            laptop_model_input: "Mod\u{00e8}le (Entr\u{00e9}e pour passer) :",
            cooling_type_prompt: "Quel type de refroidissement CPU utilisez-vous ?",
            cooling_stock: "Ventirad d'origine",
            cooling_air: "Ventirad aftermarket",
            cooling_aio: "Refroidissement AIO liquide",
            cooling_custom_loop: "Watercooling custom",
            cooling_passive: "Passif / Sans ventilateur",
            cooling_other: "Autre",
            skip: "Passer",
            enter_choice_cooling: "Entrez votre choix (1-6) ou Entr\u{00e9}e pour passer :",
            cooling_model_prompt: "Quel est votre mod\u{00e8}le de refroidisseur ? (optionnel)",
            cooling_model_examples: "ex. Noctua NH-D15, Corsair H150i, be quiet! Dark Rock Pro 4",
            cooling_model_input: "Mod\u{00e8}le (Entr\u{00e9}e pour passer) :",
            ambient_temp_prompt: "Quelle est la temp\u{00e9}rature ambiante ? (optionnel)",
            ambient_temp_hint: "Entrez un nombre en \u{00b0}C ou ajoutez 'f' pour Fahrenheit (ex. 22, 72f)",
            room_temp_input: "Temp. ambiante (Entr\u{00e9}e pour passer) :",
            cant_parse_temp: "Impossible de lire la temp\u{00e9}rature, ignor\u{00e9}.",
            extracting_sensor: "Extraction de la biblioth\u{00e8}que de capteurs...",
            sensor_ready: "Biblioth\u{00e8}que de capteurs pr\u{00ea}te (temp\u{00e9}ratures CPU pr\u{00e9}cises activ\u{00e9}es)",
            pawnio_installing: "Installation du pilote PawnIO (pawnio.eu) \u{2014} un utilitaire gratuit requis pour la lecture des temp\u{00e9}ratures CPU...",
            pawnio_installed: "Pilote PawnIO install\u{00e9} avec succ\u{00e8}s.",
            pawnio_removable: "Vous pouvez d\u{00e9}sinstaller PawnIO depuis Ajout/Suppression de programmes si vous le souhaitez.",
            pawnio_detected: "Pilote PawnIO d\u{00e9}tect\u{00e9} (pawnio.eu) \u{2014} requis pour la lecture des temp\u{00e9}ratures CPU.",
            pawnio_failed: "\u{00c9}chec de l'installation du pilote PawnIO \u{2014} les temp\u{00e9}ratures CPU pr\u{00e9}cises peuvent \u{00ea}tre indisponibles.",
            requires_admin_msg: "Cet outil n\u{00e9}cessite une ex\u{00e9}cution en tant qu'administrateur pour des temp\u{00e9}ratures CPU pr\u{00e9}cises.",
            right_click_msg: "Clic droit sur votre terminal \u{2192} Ex\u{00e9}cuter en tant qu'administrateur",
            continuing_board: "Poursuite avec les capteurs de carte m\u{00e8}re (moins pr\u{00e9}cis)...",
            idle: "Repos",
            load: "Charge",
            running_stress: "Lancement du test de stress {} pendant {}s...",
            press_ctrl_c: "Appuyez sur Ctrl+C pour arr\u{00ea}ter.",
            spawned_cpu_threads: "{} threads de stress CPU lanc\u{00e9}s",
            starting_gpu_stress: "Lancement du stress GPU (WebGPU sur {})",
            webgpu_fallback: "WebGPU non disponible ({}), utilisation du stress FP sur CPU",
            complete: "Termin\u{00e9} !",
            results_summary: "R\u{00c9}SUM\u{00c9} DES R\u{00c9}SULTATS",
            cpu_idle_label: "CPU repos :",
            cpu_load_label: "CPU charge :",
            gpu_idle_label: "GPU repos :",
            gpu_load_label: "GPU charge :",
            cpu_max_usage: "Utilisation max CPU :",
            gpu_max_usage: "Utilisation max GPU :",
            cooling_label: "Refroidissement :",
            laptop_label: "Portable :",
            cooler_label: "Refroidisseur :",
            ambient_label: "Ambiante :",
            label_stock: "Ventirad d'origine",
            label_air: "Aftermarket air",
            label_aio: "AIO liquide",
            label_custom_loop: "Boucle custom",
            label_passive: "Passif / Sans ventilateur",
            label_other: "Autre",
            board_sensor_warning: "La temp\u{00e9}rature CPU n'a pas chang\u{00e9} \u{2014} lecture depuis un capteur de carte m\u{00e8}re.",
            rerun_admin: "Relancez en tant qu'administrateur pour des temp\u{00e9}ratures CPU pr\u{00e9}cises.",
            submitting: "Soumission des r\u{00e9}sultats...",
            submitted_view: "Soumis ! Voir sur :",
            prod_unreachable: "API de production inaccessible, essai en local...",
            submitted_local: "Soumis au serveur local ! Voir sur :",
            failed_submit: "\u{00c9}chec de la soumission :",
            not_saved_online: "Les r\u{00e9}sultats ont \u{00e9}t\u{00e9} affich\u{00e9}s ci-dessus mais non sauvegard\u{00e9}s en ligne.",
            skipping_submit: "Soumission ignor\u{00e9}e (option --no-submit).",
            stale_temps_skip: "Soumission ignor\u{00e9}e \u{2014} la temp\u{00e9}rature CPU n'a pas chang\u{00e9} entre repos et charge.\n  Relancez en tant qu'administrateur pour des temp\u{00e9}ratures CPU pr\u{00e9}cises.",
            api_rejected: "Soumission refus\u{00e9}e :",
            done: "Termin\u{00e9} !",
            window_closing: "La fen\u{00ea}tre se fermera dans 30 secondes. Appuyez sur Ctrl+C pour quitter.",
            closing_in: "Fermeture dans {}s...",
            goodbye: "Au revoir !",
            opening_browser: "Ouverture des r\u{00e9}sultats dans votre navigateur...",
            pawnio_keep_prompt: "Voulez-vous laisser le pilote PawnIO install\u{00e9} ? C'est un pilote l\u{00e9}ger, gratuit\n  et open-source utile pour la surveillance mat\u{00e9}rielle. (https://github.com/namazso/PawnIO)",
            pawnio_keep_yes: "Oui, garder install\u{00e9}",
            pawnio_keep_no: "Non, d\u{00e9}sinstaller",
            pawnio_keep_timeout: "Pas de r\u{00e9}ponse en {}s \u{2014} PawnIO restera install\u{00e9}.",
            pawnio_enter_choice: "Entrez votre choix (1-2) \u{2014} par d\u{00e9}faut 1 dans {}s :",
            pawnio_kept: "Le pilote PawnIO restera install\u{00e9}.",
            pawnio_uninstalling: "D\u{00e9}sinstallation du pilote PawnIO...",
            pawnio_uninstalled: "Pilote PawnIO d\u{00e9}sinstall\u{00e9}.",
            pawnio_uninstall_failed: "\u{00c9}chec de la d\u{00e9}sinstallation de PawnIO :",
        }
    }

    fn es() -> Self {
        Self {
            invalid_test_type: "Tipo de prueba inv\u{00e1}lido '{}'. Use: cpu, gpu o both",
            invalid_cooling_type: "Tipo de refrigeraci\u{00f3}n inv\u{00e1}lido '{}'. Use: stock, air, aio, custom_loop, passive u other",
            detecting_hardware: "Detectando hardware...",
            laptop_detected: "Port\u{00e1}til detectado",
            unknown: "Desconocido",
            not_available: "No disponible",
            what_to_test: "\u{00bf}Qu\u{00e9} desea probar?",
            cpu_only: "Solo CPU",
            gpu_only: "Solo GPU",
            cpu_gpu_recommended: "CPU + GPU (recomendado)",
            enter_choice_test: "Ingrese su opci\u{00f3}n (1/2/3)",
            how_long_stress: "\u{00bf}Cu\u{00e1}nto tiempo debe durar la prueba de estr\u{00e9}s?",
            recommend_note: "Recomendamos al menos 120 segundos para que la refrigeraci\u{00f3}n",
            recommend_reason: "se estabilice y proporcione temperaturas realistas.",
            dur_60: " 60 segundos  (r\u{00e1}pido)",
            dur_120: "120 segundos  (recomendado)",
            dur_180: "180 segundos  (completo)",
            dur_300: "300 segundos  (extendido)",
            dur_custom: "Personalizado",
            enter_choice_duration: "Ingrese su opci\u{00f3}n (1-5)",
            enter_duration_secs: "Ingrese la duraci\u{00f3}n en segundos:",
            min_duration_30: "Duraci\u{00f3}n m\u{00ed}nima de 30 segundos, usando 30s.",
            laptop_model_prompt: "\u{00bf}Qu\u{00e9} modelo de port\u{00e1}til tiene? (opcional)",
            laptop_model_examples: "ej. ASUS ROG Zephyrus G14, Dell XPS 15, Lenovo Legion 5 Pro",
            laptop_model_input: "Modelo (Enter para omitir):",
            cooling_type_prompt: "\u{00bf}Qu\u{00e9} tipo de refrigeraci\u{00f3}n de CPU usa?",
            cooling_stock: "Disipador de serie",
            cooling_air: "Disipador de aire aftermarket",
            cooling_aio: "Refrigeraci\u{00f3}n l\u{00ed}quida AIO",
            cooling_custom_loop: "Circuito de agua custom",
            cooling_passive: "Pasivo / Sin ventilador",
            cooling_other: "Otro",
            skip: "Omitir",
            enter_choice_cooling: "Ingrese su opci\u{00f3}n (1-6) o Enter para omitir:",
            cooling_model_prompt: "\u{00bf}Qu\u{00e9} modelo de disipador tiene? (opcional)",
            cooling_model_examples: "ej. Noctua NH-D15, Corsair H150i, be quiet! Dark Rock Pro 4",
            cooling_model_input: "Modelo (Enter para omitir):",
            ambient_temp_prompt: "\u{00bf}Cu\u{00e1}l es la temperatura ambiente? (opcional)",
            ambient_temp_hint: "Ingrese un n\u{00fa}mero en \u{00b0}C o a\u{00f1}ada 'f' para Fahrenheit (ej. 22, 72f)",
            room_temp_input: "Temp. ambiente (Enter para omitir):",
            cant_parse_temp: "No se pudo leer la temperatura, omitido.",
            extracting_sensor: "Extrayendo biblioteca de sensores...",
            sensor_ready: "Biblioteca de sensores lista (temperaturas CPU precisas activadas)",
            pawnio_installing: "Instalando controlador PawnIO (pawnio.eu) \u{2014} una utilidad gratuita necesaria para la lectura de temperaturas de la CPU...",
            pawnio_installed: "Controlador PawnIO instalado correctamente.",
            pawnio_removable: "Puede desinstalar PawnIO desde Agregar o quitar programas si lo desea.",
            pawnio_detected: "Controlador PawnIO detectado (pawnio.eu) \u{2014} necesario para la lectura de temperaturas de la CPU.",
            pawnio_failed: "Error al instalar el controlador PawnIO \u{2014} las temperaturas precisas de la CPU pueden no estar disponibles.",
            requires_admin_msg: "Esta herramienta requiere ejecutarse como Administrador para temperaturas CPU precisas.",
            right_click_msg: "Clic derecho en su terminal \u{2192} Ejecutar como administrador",
            continuing_board: "Continuando con sensores de placa base (menos preciso)...",
            idle: "Reposo",
            load: "Carga",
            running_stress: "Ejecutando prueba de estr\u{00e9}s {} durante {}s...",
            press_ctrl_c: "Presione Ctrl+C para detener.",
            spawned_cpu_threads: "{} hilos de estr\u{00e9}s CPU lanzados",
            starting_gpu_stress: "Iniciando estr\u{00e9}s GPU (WebGPU en {})",
            webgpu_fallback: "WebGPU no disponible ({}), usando estr\u{00e9}s FP en CPU",
            complete: "\u{00a1}Completo!",
            results_summary: "RESUMEN DE RESULTADOS",
            cpu_idle_label: "CPU Reposo:",
            cpu_load_label: "CPU Carga:",
            gpu_idle_label: "GPU Reposo:",
            gpu_load_label: "GPU Carga:",
            cpu_max_usage: "Uso m\u{00e1}x CPU:",
            gpu_max_usage: "Uso m\u{00e1}x GPU:",
            cooling_label: "Refrigeraci\u{00f3}n:",
            laptop_label: "Port\u{00e1}til:",
            cooler_label: "Disipador:",
            ambient_label: "Ambiente:",
            label_stock: "Disipador de serie",
            label_air: "Aftermarket aire",
            label_aio: "AIO l\u{00ed}quido",
            label_custom_loop: "Circuito custom",
            label_passive: "Pasivo / Sin ventilador",
            label_other: "Otro",
            board_sensor_warning: "La temperatura CPU no cambi\u{00f3} \u{2014} lectura de un sensor de placa base.",
            rerun_admin: "Ejecute de nuevo como Administrador para temperaturas CPU precisas.",
            submitting: "Enviando resultados...",
            submitted_view: "\u{00a1}Enviado! Ver en:",
            prod_unreachable: "API de producci\u{00f3}n inaccesible, intentando localhost...",
            submitted_local: "\u{00a1}Enviado al servidor local! Ver en:",
            failed_submit: "Error al enviar:",
            not_saved_online: "Los resultados se mostraron arriba pero no se guardaron en l\u{00ed}nea.",
            skipping_submit: "Env\u{00ed}o omitido (opci\u{00f3}n --no-submit).",
            stale_temps_skip: "Env\u{00ed}o omitido \u{2014} la temperatura CPU no cambi\u{00f3} entre reposo y carga.\n  Ejecute de nuevo como Administrador para temperaturas CPU precisas.",
            api_rejected: "Env\u{00ed}o rechazado:",
            done: "\u{00a1}Listo!",
            window_closing: "La ventana se cerrar\u{00e1} en 30 segundos. Presione Ctrl+C para salir.",
            closing_in: "Cerrando en {}s...",
            goodbye: "\u{00a1}Adi\u{00f3}s!",
            opening_browser: "Abriendo resultados en su navegador...",
            pawnio_keep_prompt: "\u{00bf}Desea dejar el controlador PawnIO instalado? Es un controlador ligero, gratuito\n  y de c\u{00f3}digo abierto \u{00fa}til para monitoreo de hardware. (https://github.com/namazso/PawnIO)",
            pawnio_keep_yes: "S\u{00ed}, mantener instalado",
            pawnio_keep_no: "No, desinstalar",
            pawnio_keep_timeout: "Sin respuesta en {}s \u{2014} PawnIO permanecer\u{00e1} instalado.",
            pawnio_enter_choice: "Ingrese su opci\u{00f3}n (1-2) \u{2014} por defecto 1 en {}s:",
            pawnio_kept: "El controlador PawnIO permanecer\u{00e1} instalado.",
            pawnio_uninstalling: "Desinstalando controlador PawnIO...",
            pawnio_uninstalled: "Controlador PawnIO desinstalado.",
            pawnio_uninstall_failed: "Error al desinstalar PawnIO:",
        }
    }

    fn de() -> Self {
        Self {
            invalid_test_type: "Ung\u{00fc}ltiger Testtyp '{}'. Verwenden Sie: cpu, gpu oder both",
            invalid_cooling_type: "Ung\u{00fc}ltiger K\u{00fc}hlungstyp '{}'. Verwenden Sie: stock, air, aio, custom_loop, passive oder other",
            detecting_hardware: "Hardware wird erkannt...",
            laptop_detected: "Laptop erkannt",
            unknown: "Unbekannt",
            not_available: "Nicht verf\u{00fc}gbar",
            what_to_test: "Was m\u{00f6}chten Sie testen?",
            cpu_only: "Nur CPU",
            gpu_only: "Nur GPU",
            cpu_gpu_recommended: "CPU + GPU (empfohlen)",
            enter_choice_test: "Auswahl eingeben (1/2/3)",
            how_long_stress: "Wie lange soll der Stresstest laufen?",
            recommend_note: "Wir empfehlen mindestens 120 Sekunden, damit die K\u{00fc}hlung",
            recommend_reason: "sich stabilisieren und realistische Temperaturen liefern kann.",
            dur_60: " 60 Sekunden  (schnell)",
            dur_120: "120 Sekunden  (empfohlen)",
            dur_180: "180 Sekunden  (gr\u{00fc}ndlich)",
            dur_300: "300 Sekunden  (erweitert)",
            dur_custom: "Benutzerdefiniert",
            enter_choice_duration: "Auswahl eingeben (1-5)",
            enter_duration_secs: "Dauer in Sekunden eingeben:",
            min_duration_30: "Mindestdauer betr\u{00e4}gt 30 Sekunden, verwende 30s.",
            laptop_model_prompt: "Welches Laptop-Modell haben Sie? (optional)",
            laptop_model_examples: "z.B. ASUS ROG Zephyrus G14, Dell XPS 15, Lenovo Legion 5 Pro",
            laptop_model_input: "Modell (Enter zum \u{00dc}berspringen):",
            cooling_type_prompt: "Welche Art von CPU-K\u{00fc}hlung verwenden Sie?",
            cooling_stock: "Standard-K\u{00fc}hler",
            cooling_air: "Aftermarket-Luftk\u{00fc}hler",
            cooling_aio: "AIO-Wasserk\u{00fc}hlung",
            cooling_custom_loop: "Custom-Wasserkreislauf",
            cooling_passive: "Passiv / L\u{00fc}fterlos",
            cooling_other: "Andere",
            skip: "\u{00dc}berspringen",
            enter_choice_cooling: "Auswahl eingeben (1-6) oder Enter zum \u{00dc}berspringen:",
            cooling_model_prompt: "Welches K\u{00fc}hlermodell haben Sie? (optional)",
            cooling_model_examples: "z.B. Noctua NH-D15, Corsair H150i, be quiet! Dark Rock Pro 4",
            cooling_model_input: "Modell (Enter zum \u{00dc}berspringen):",
            ambient_temp_prompt: "Wie hoch ist Ihre Raumtemperatur? (optional)",
            ambient_temp_hint: "Geben Sie eine Zahl in \u{00b0}C ein oder f\u{00fc}gen Sie 'f' f\u{00fc}r Fahrenheit hinzu (z.B. 22, 72f)",
            room_temp_input: "Raumtemp. (Enter zum \u{00dc}berspringen):",
            cant_parse_temp: "Temperatur konnte nicht gelesen werden, \u{00fc}bersprungen.",
            extracting_sensor: "Sensorbibliothek wird extrahiert...",
            sensor_ready: "Sensorbibliothek bereit (genaue CPU-Temperaturen aktiviert)",
            pawnio_installing: "PawnIO-Treiber wird installiert (pawnio.eu) \u{2014} ein kostenloses Hilfsprogramm f\u{00fc}r die CPU-Temperaturmessung...",
            pawnio_installed: "PawnIO-Treiber erfolgreich installiert.",
            pawnio_removable: "Sie k\u{00f6}nnen PawnIO \u{00fc}ber Programme hinzuf\u{00fc}gen/entfernen deinstallieren, wenn Sie m\u{00f6}chten.",
            pawnio_detected: "PawnIO-Treiber erkannt (pawnio.eu) \u{2014} erforderlich f\u{00fc}r die CPU-Temperaturmessung.",
            pawnio_failed: "PawnIO-Treiberinstallation fehlgeschlagen \u{2014} genaue CPU-Temperaturen m\u{00f6}glicherweise nicht verf\u{00fc}gbar.",
            requires_admin_msg: "Dieses Tool erfordert Ausf\u{00fc}hrung als Administrator f\u{00fc}r genaue CPU-Temperaturen.",
            right_click_msg: "Rechtsklick auf Ihr Terminal \u{2192} Als Administrator ausf\u{00fc}hren",
            continuing_board: "Fortfahren mit Mainboard-Sensoren (weniger genau)...",
            idle: "Leerlauf",
            load: "Last",
            running_stress: "{} Stresstest l\u{00e4}uft f\u{00fc}r {}s...",
            press_ctrl_c: "Dr\u{00fc}cken Sie Strg+C zum Abbrechen.",
            spawned_cpu_threads: "{} CPU-Stressthreads gestartet",
            starting_gpu_stress: "GPU-Stress wird gestartet (WebGPU auf {})",
            webgpu_fallback: "WebGPU nicht verf\u{00fc}gbar ({}), verwende CPU-basierten FP-Stress",
            complete: "Abgeschlossen!",
            results_summary: "ERGEBNIS\u{00dc}BERSICHT",
            cpu_idle_label: "CPU Leerlauf:",
            cpu_load_label: "CPU Last:",
            gpu_idle_label: "GPU Leerlauf:",
            gpu_load_label: "GPU Last:",
            cpu_max_usage: "Max CPU-Auslastung:",
            gpu_max_usage: "Max GPU-Auslastung:",
            cooling_label: "K\u{00fc}hlung:",
            laptop_label: "Laptop:",
            cooler_label: "K\u{00fc}hler:",
            ambient_label: "Umgebung:",
            label_stock: "Standard-K\u{00fc}hler",
            label_air: "Aftermarket-Luft",
            label_aio: "AIO-Fl\u{00fc}ssig",
            label_custom_loop: "Custom-Kreislauf",
            label_passive: "Passiv / L\u{00fc}fterlos",
            label_other: "Andere",
            board_sensor_warning: "CPU-Temperatur hat sich nicht ge\u{00e4}ndert \u{2014} Messung vom Mainboard-Sensor.",
            rerun_admin: "Erneut als Administrator ausf\u{00fc}hren f\u{00fc}r genaue CPU-Temperaturen.",
            submitting: "Ergebnisse werden \u{00fc}bermittelt...",
            submitted_view: "\u{00dc}bermittelt! Ansehen unter:",
            prod_unreachable: "Produktions-API nicht erreichbar, versuche localhost...",
            submitted_local: "An lokalen Server \u{00fc}bermittelt! Ansehen unter:",
            failed_submit: "Fehler beim \u{00dc}bermitteln:",
            not_saved_online: "Ergebnisse wurden oben angezeigt, aber nicht online gespeichert.",
            skipping_submit: "\u{00dc}bermittlung \u{00fc}bersprungen (--no-submit).",
            stale_temps_skip: "\u{00dc}bermittlung \u{00fc}bersprungen \u{2014} CPU-Temperatur hat sich zwischen Leerlauf und Last nicht ge\u{00e4}ndert.\n  Erneut als Administrator ausf\u{00fc}hren f\u{00fc}r genaue CPU-Temperaturen.",
            api_rejected: "\u{00dc}bermittlung abgelehnt:",
            done: "Fertig!",
            window_closing: "Fenster schlie\u{00df}t in 30 Sekunden. Dr\u{00fc}cken Sie Strg+C zum Beenden.",
            closing_in: "Schlie\u{00df}t in {}s...",
            goodbye: "Auf Wiedersehen!",
            opening_browser: "Ergebnisse werden im Browser ge\u{00f6}ffnet...",
            pawnio_keep_prompt: "M\u{00f6}chten Sie den PawnIO-Treiber installiert lassen? Er ist ein leichtgewichtiger,\n  kostenloser Open-Source-Treiber f\u{00fc}r Hardware-\u{00dc}berwachung. (https://github.com/namazso/PawnIO)",
            pawnio_keep_yes: "Ja, installiert lassen",
            pawnio_keep_no: "Nein, deinstallieren",
            pawnio_keep_timeout: "Keine Antwort in {}s \u{2014} PawnIO bleibt installiert.",
            pawnio_enter_choice: "Auswahl eingeben (1-2) \u{2014} Standard 1 in {}s:",
            pawnio_kept: "PawnIO-Treiber bleibt installiert.",
            pawnio_uninstalling: "PawnIO-Treiber wird deinstalliert...",
            pawnio_uninstalled: "PawnIO-Treiber deinstalliert.",
            pawnio_uninstall_failed: "PawnIO-Deinstallation fehlgeschlagen:",
        }
    }

    fn pt() -> Self {
        Self {
            invalid_test_type: "Tipo de teste inv\u{00e1}lido '{}'. Use: cpu, gpu ou both",
            invalid_cooling_type: "Tipo de refrigera\u{00e7}\u{00e3}o inv\u{00e1}lido '{}'. Use: stock, air, aio, custom_loop, passive ou other",
            detecting_hardware: "Detectando hardware...",
            laptop_detected: "Notebook detectado",
            unknown: "Desconhecido",
            not_available: "N\u{00e3}o dispon\u{00ed}vel",
            what_to_test: "O que deseja testar?",
            cpu_only: "Apenas CPU",
            gpu_only: "Apenas GPU",
            cpu_gpu_recommended: "CPU + GPU (recomendado)",
            enter_choice_test: "Insira sua escolha (1/2/3)",
            how_long_stress: "Quanto tempo o teste de estresse deve durar?",
            recommend_note: "Recomendamos pelo menos 120 segundos para que a refrigera\u{00e7}\u{00e3}o",
            recommend_reason: "se estabilize e forne\u{00e7}a temperaturas realistas.",
            dur_60: " 60 segundos  (r\u{00e1}pido)",
            dur_120: "120 segundos  (recomendado)",
            dur_180: "180 segundos  (completo)",
            dur_300: "300 segundos  (estendido)",
            dur_custom: "Personalizado",
            enter_choice_duration: "Insira sua escolha (1-5)",
            enter_duration_secs: "Insira a dura\u{00e7}\u{00e3}o em segundos:",
            min_duration_30: "Dura\u{00e7}\u{00e3}o m\u{00ed}nima de 30 segundos, usando 30s.",
            laptop_model_prompt: "Qual \u{00e9} o modelo do seu notebook? (opcional)",
            laptop_model_examples: "ex. ASUS ROG Zephyrus G14, Dell XPS 15, Lenovo Legion 5 Pro",
            laptop_model_input: "Modelo (Enter para pular):",
            cooling_type_prompt: "Que tipo de refrigera\u{00e7}\u{00e3}o de CPU voc\u{00ea} usa?",
            cooling_stock: "Cooler de f\u{00e1}brica",
            cooling_air: "Cooler de ar aftermarket",
            cooling_aio: "Refrigera\u{00e7}\u{00e3}o l\u{00ed}quida AIO",
            cooling_custom_loop: "Circuito de \u{00e1}gua custom",
            cooling_passive: "Passivo / Sem ventilador",
            cooling_other: "Outro",
            skip: "Pular",
            enter_choice_cooling: "Insira sua escolha (1-6) ou Enter para pular:",
            cooling_model_prompt: "Qual \u{00e9} o modelo do seu cooler? (opcional)",
            cooling_model_examples: "ex. Noctua NH-D15, Corsair H150i, be quiet! Dark Rock Pro 4",
            cooling_model_input: "Modelo (Enter para pular):",
            ambient_temp_prompt: "Qual \u{00e9} a temperatura ambiente? (opcional)",
            ambient_temp_hint: "Insira um n\u{00fa}mero em \u{00b0}C ou adicione 'f' para Fahrenheit (ex. 22, 72f)",
            room_temp_input: "Temp. ambiente (Enter para pular):",
            cant_parse_temp: "N\u{00e3}o foi poss\u{00ed}vel ler a temperatura, ignorado.",
            extracting_sensor: "Extraindo biblioteca de sensores...",
            sensor_ready: "Biblioteca de sensores pronta (temperaturas CPU precisas ativadas)",
            pawnio_installing: "Instalando driver PawnIO (pawnio.eu) \u{2014} um utilit\u{00e1}rio gratuito necess\u{00e1}rio para a leitura de temperaturas da CPU...",
            pawnio_installed: "Driver PawnIO instalado com sucesso.",
            pawnio_removable: "Voc\u{00ea} pode desinstalar o PawnIO em Adicionar/Remover Programas, se desejar.",
            pawnio_detected: "Driver PawnIO detectado (pawnio.eu) \u{2014} necess\u{00e1}rio para a leitura de temperaturas da CPU.",
            pawnio_failed: "Falha na instala\u{00e7}\u{00e3}o do driver PawnIO \u{2014} temperaturas precisas da CPU podem n\u{00e3}o estar dispon\u{00ed}veis.",
            requires_admin_msg: "Esta ferramenta requer execu\u{00e7}\u{00e3}o como Administrador para temperaturas CPU precisas.",
            right_click_msg: "Clique com o bot\u{00e3}o direito no terminal \u{2192} Executar como administrador",
            continuing_board: "Continuando com sensores da placa-m\u{00e3}e (menos preciso)...",
            idle: "Repouso",
            load: "Carga",
            running_stress: "Executando teste de estresse {} por {}s...",
            press_ctrl_c: "Pressione Ctrl+C para parar.",
            spawned_cpu_threads: "{} threads de estresse CPU iniciados",
            starting_gpu_stress: "Iniciando estresse GPU (WebGPU em {})",
            webgpu_fallback: "WebGPU n\u{00e3}o dispon\u{00ed}vel ({}), usando estresse FP em CPU",
            complete: "Completo!",
            results_summary: "RESUMO DOS RESULTADOS",
            cpu_idle_label: "CPU Repouso:",
            cpu_load_label: "CPU Carga:",
            gpu_idle_label: "GPU Repouso:",
            gpu_load_label: "GPU Carga:",
            cpu_max_usage: "Uso m\u{00e1}x CPU:",
            gpu_max_usage: "Uso m\u{00e1}x GPU:",
            cooling_label: "Refrigera\u{00e7}\u{00e3}o:",
            laptop_label: "Notebook:",
            cooler_label: "Cooler:",
            ambient_label: "Ambiente:",
            label_stock: "Cooler de f\u{00e1}brica",
            label_air: "Aftermarket ar",
            label_aio: "AIO l\u{00ed}quido",
            label_custom_loop: "Circuito custom",
            label_passive: "Passivo / Sem ventilador",
            label_other: "Outro",
            board_sensor_warning: "A temperatura da CPU n\u{00e3}o mudou \u{2014} leitura de um sensor da placa-m\u{00e3}e.",
            rerun_admin: "Execute novamente como Administrador para temperaturas CPU precisas.",
            submitting: "Enviando resultados...",
            submitted_view: "Enviado! Ver em:",
            prod_unreachable: "API de produ\u{00e7}\u{00e3}o inacess\u{00ed}vel, tentando localhost...",
            submitted_local: "Enviado ao servidor local! Ver em:",
            failed_submit: "Falha ao enviar:",
            not_saved_online: "Os resultados foram exibidos acima mas n\u{00e3}o foram salvos online.",
            skipping_submit: "Envio ignorado (op\u{00e7}\u{00e3}o --no-submit).",
            stale_temps_skip: "Envio ignorado \u{2014} a temperatura da CPU n\u{00e3}o mudou entre repouso e carga.\n  Execute novamente como Administrador para temperaturas CPU precisas.",
            api_rejected: "Envio rejeitado:",
            done: "Pronto!",
            window_closing: "A janela fechar\u{00e1} em 30 segundos. Pressione Ctrl+C para sair.",
            closing_in: "Fechando em {}s...",
            goodbye: "Adeus!",
            opening_browser: "Abrindo resultados no seu navegador...",
            pawnio_keep_prompt: "Deseja manter o driver PawnIO instalado? \u{00c9} um driver leve, gratuito\n  e de c\u{00f3}digo aberto \u{00fa}til para monitoramento de hardware. (https://github.com/namazso/PawnIO)",
            pawnio_keep_yes: "Sim, manter instalado",
            pawnio_keep_no: "N\u{00e3}o, desinstalar",
            pawnio_keep_timeout: "Sem resposta em {}s \u{2014} PawnIO permanecer\u{00e1} instalado.",
            pawnio_enter_choice: "Insira sua escolha (1-2) \u{2014} padr\u{00e3}o 1 em {}s:",
            pawnio_kept: "O driver PawnIO permanecer\u{00e1} instalado.",
            pawnio_uninstalling: "Desinstalando driver PawnIO...",
            pawnio_uninstalled: "Driver PawnIO desinstalado.",
            pawnio_uninstall_failed: "Falha ao desinstalar PawnIO:",
        }
    }
}
